name: lanta-cv
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - tqdm
  - pip:
      - ultralytics
      - opencv-python
      - pillow
      - pyyaml
