name: cvhack
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - pillow
  - tqdm
  - pyyaml
  - jupyter
  - nbconvert
  - pip:
      - ultralytics
      - opencv-python-headless
